---
title: "Ratings"
output: html_document
date: "2024-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(GGally)

data <- read_csv("processed.csv")
mi_full <- read_csv("condmutualinfo.csv")
game1 <- read_csv("imageSample.csv")
```

```{r}
head(data)
```

```{r}
# get count of raters for each image
data %>%
  count(rateDim, image) %>%
  arrange(n) %>%
  filter(n < 3) %>%
  nrow()
# 16 images with less than 3 raters

data %>%
  count(rateDim, image) %>%
  arrange(desc(n))
# highest with 20 raters


data %>%
  count(rateDim, image) %>%
  summarise(mean = mean(n),
            sd = sd(n))
```


```{r}
# sample 30 participants
sampSubjs <- data %>%
  distinct(subjID) %>%
  sample_n(30) %>%
  pull(subjID)

# examine variance in human uses of rating system
data %>%
  filter(subjID %in% sampSubjs) %>%
  ggplot(aes(x=zscore)) +
  geom_histogram() +
  facet_wrap(~subjID)
```

```{r}
# examine variance in ratings for select images
data %>%
  filter(levelID == "basic_far", wind == "none") %>%
  ggplot(aes(x=zscore, fill=rateDim)) +
  geom_density(alpha=0.5) +
  facet_wrap(~designer, nrow=3) +
  theme_bw()

data %>%
  filter(levelID == "boomerang_middle", wind == "none") %>%
  ggplot(aes(x=zscore, fill=rateDim)) +
  geom_density(alpha=0.5) +
  facet_wrap(~designer, nrow=3) +
  theme_bw()
```

```{r}
# least cool solutions as rated by people with wind
data %>%
  group_by(ratedImg) %>%
  filter(rateDim == "unique" & wind != "none" & levelID == "boomerang_middle") %>%
  summarise(meanzscore = mean(zscore)) %>%
  arrange(desc(meanzscore))

# coolest solutions as rated by people without wind
data %>%
  group_by(ratedImg) %>%
  filter(rateDim == "unique" & wind == "none" & levelID == "basic_far") %>%
  summarise(meanzscore = mean(zscore)) %>%
  arrange(desc(meanzscore))
```

## Process mutualinfo file
```{r}
mi_df <- mi_full %>%
  select(-`...1`) %>%
  rename(image = imageID)

data <- data %>%
  left_join(mi_df, by=c("levelID","image"))
```

```{r}
data %>%
  group_by(levelID, rateDim, image, cond_mutualinfo) %>%
  summarise(mean_human = mean(zscore),
            se = sd(zscore)/sqrt(n())) %>%
  ggplot(aes(x=cond_mutualinfo, y=mean_human)) +
  geom_pointrange(aes(ymin = mean_human-se, ymax = mean_human+se), size=0.1) +
  geom_smooth() +
  facet_wrap(~rateDim)

```

```{r}
# correlations between measures
# data %>%
#   group_by(rateDim, image, cond_mutualinfo) %>%
#   summarise(mean = mean(zscore)) %>%
#   spread(rateDim, mean) %>%
#   ungroup() %>%
#   select(-image) %>%
#   ggpairs(lower=list(continuous=wrap("smooth", colour="blue")))

ratings <- data %>%
  group_by(rateDim, image) %>%
  summarise(mean = mean(zscore)) %>%
  spread(rateDim, mean) %>%
  ungroup() %>%
  select(-image)

ggpairs(ratings, lower=list(continuous=wrap("smooth", colour="blue"))) +
  theme_classic()
ggsave("fig/ratecorrs.png", width=6, height=6)

cor.test(ratings$feasible, ratings$cool)
cor.test(ratings$unique, ratings$cool)
cor.test(ratings$unique, ratings$feasible)
```

# are certain levels more X
```{r}
# standard errors
ggplot(data, aes(x=levelID, y=zscore)) +
  geom_pointrange(stat="summary", position=position_dodge(0.9), size=0.05) +
  geom_hline(yintercept=0, alpha=0.4, colour="red") +
  facet_grid(rateDim ~ .) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

# confidence intervals

data %>%
  group_by(rateDim, levelID) %>%
  summarise(mean = mean(zscore),
            se = sd(zscore)/sqrt(n()),
            lower_ci = mean - 1.96*se,
            upper_ci = mean + 1.96*se) %>%
  ggplot(aes(x=levelID, y=mean)) +
  geom_pointrange(aes(ymin = lower_ci, ymax=upper_ci), position=position_dodge(0.9), size=0.05) +
  geom_hline(yintercept=0, alpha=0.4, colour="red") +
  facet_grid(rateDim ~ .) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


data %>%
  group_by(rateDim, levelID, image) %>%
  summarise(mean = mean(zscore)) %>%
  ggplot(aes(x=levelID, y=mean)) +
  geom_dotplot(binaxis = "y", stackdir = "center", alpha=0.3, fill="blue") +
  geom_pointrange(stat="summary", position=position_dodge(0.9), size=0.05) +
  geom_hline(yintercept=0, alpha=0.4, colour="red") +
  facet_grid(rateDim ~ .) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

```{r}
# dotplot for boomerang_middle, none
data %>%
  filter(levelID == "boomerang_middle" & rateDim == "cool") %>%
  group_by(image) %>%
  summarise(mean = mean(zscore)) %>%
  ggplot(aes(x="boomerang", y=mean)) +
  geom_dotplot(binaxis = "y", stackdir = "center", alpha=0.3, fill="red", colour="red") +
  geom_pointrange(stat="summary", position=position_dodge(0.9), size=0.05) +
  geom_hline(yintercept=0, alpha=0.4, colour="grey38") +
  scale_x_discrete("") +
  scale_y_continuous("human rated coolness (z-scored)") +
  theme_bw() +
  theme(axis.text.x = element_text(size=20),
        axis.title.y = element_text(size=20))
ggsave("fig/boomerang_cool.png", width=2.5, height=5)

data %>%
  filter(levelID == "boomerang_middle" & rateDim == "cool") %>%
  group_by(levelID, wind, image) %>%
  summarise(mean = mean(zscore)) %>%
  arrange(desc(mean))

data %>%
  filter(image == "connect-512FED05A72842BF9658B966FBD7F076_img11.png")
```

```{r}
successData <- game1 %>%
  select(imageID, trainingCond, numAttempts, success, numStrokes) %>%
  rename(image = imageID)

fullsuccess <- data %>%
  left_join(successData, by="image") %>%
  mutate(successNum = as.numeric(success == "success"))
```


```{r}
fullsuccess %>%
  filter(rateDim == "feasible") %>%
  group_by(image, success) %>%
  summarise(feasibility = mean(zscore)) %>%
  ggplot(aes(x=success, y=feasibility, fill=success)) +
  geom_violin() +
  geom_pointrange(stat="summary", position=position_dodge(0.9), size=0.05) +
  scale_fill_manual(values=c("red","forestgreen")) +
  scale_y_continuous()

fullsuccess %>%
  filter(rateDim == "feasible") %>%
  # group_by(image, success) %>%
  # summarise(feasibility = mean(zscore)) %>%
  ggplot(aes(x=success, y=zscore, fill=success)) +
  geom_violin() +
  geom_pointrange(stat="summary", position=position_dodge(0.9), size=0.05) +
  scale_fill_manual(values=c("red","forestgreen")) +
  scale_y_continuous()
```

```{r}
fullsuccess %>%
  group_by(levelID, rateDim, image, cond_mutualinfo, success) %>%
  summarise(mean_human = mean(zscore),
            se = sd(zscore)/sqrt(n())) %>%
  ggplot(aes(x=cond_mutualinfo, y=mean_human)) +
  geom_pointrange(aes(ymin = mean_human-se, ymax = mean_human+se), size=0.1) +
  geom_smooth() +
  facet_grid(rateDim~success)
```


